#!/usr/bin/env python3
"""Generate the fixture PDFs used by the Windows headless harness.

    portable/win/tests/make_fixture_pdf.py [out.pdf]              # golden.pdf
    portable/win/tests/make_fixture_pdf.py --kind alpha [out.pdf] # alpha.pdf
    portable/win/tests/make_fixture_pdf.py --all <dir>            # both, in place

Both fixtures are committed, so this script exists to document how they were made
and to let them be regenerated byte-for-byte. It writes hand-assembled,
uncompressed PDFs: no MuPDF, no reportlab, no dependency that could drift and
silently change a golden image under the tests.

THERE ARE TWO FIXTURES BECAUSE ONE CANNOT DO BOTH JOBS.

golden.pdf paints an opaque white background and renders FULLY OPAQUE -- every
pixel alpha 255. That is right for what it tests (flip, channel swap, scale,
anti-aliasing) and it is precisely why it cannot test the other half:
premultiplying a fully opaque image is the identity transform, and a
transparent-pixel halo needs transparent pixels. Pointed at golden.pdf alone,
the comparator's two alpha detectors -- the two aimed at the premultiplied-alpha
halo this repo has already shipped once -- could never fire, on any run, however
broken the render.

alpha.pdf is the fixture that makes them live. See build_alpha().

WHY THE PAGE LOOKS LIKE THIS. Every element is here to make one specific port
bug visible in a pixel comparison; nothing is decorative.

  * Asymmetric top-to-bottom (red band high, blue band low) so a VERTICAL FLIP
    -- the single most common bug when moving between a y-up rasteriser and a
    y-down blit target -- turns into a large, obvious colour difference rather
    than a subtle one. A vertically symmetric fixture would hide it completely.
  * Pure-red and pure-blue regions of unequal area so an RGB/BGR CHANNEL SWAP
    is unmissable and is not confusable with the flip (the flip moves the bands,
    the swap recolours them in place).
  * A green block and a black/grey ramp so a swap that only touches R and B is
    still distinguishable from one that touches all three.
  * Text and hairline rules so ANTI-ALIASING and hinting differences between the
    two rasterisers show up somewhere, and the tolerance can be measured on real
    glyph edges instead of on flat fill.
  * Page 2 is deliberately a different size from page 1, so a probe that reports
    only one page size, or a layout that assumes uniform pages, fails loudly.

Page 1 is 200x260 pt, page 2 is 300x160 pt. Small on purpose: the whole point is
that a render at zoom 2 is a few hundred KB, so a golden PNG can live in git.
"""

import os
import sys

# Content stream for page 1. PDF user space: origin bottom-left, y increases UP.
# So "top" here means high y.
PAGE1 = b"""q
1 1 1 rg 0 0 200 260 re f
1 0 0 rg 10 200 180 50 re f
0 0.65 0 rg 10 150 80 40 re f
0.5 0.5 0.5 rg 100 150 90 40 re f
0 0 1 rg 10 60 180 40 re f
0 0.55 0.6 rg 10 20 90 40 re f
0.8 0 0.55 rg 100 20 90 40 re f
0 g
BT /F1 18 Tf 16 118 Td (SPDF WIN) Tj ET
BT /F1 9 Tf 16 106 Td (golden fixture page 1) Tj ET
0 g 1 w 10 136 m 190 136 l S
0 g 0.4 w 10 112 m 190 112 l S
0 0 0 rg 150 210 30 30 re f
1 1 1 rg 158 218 14 14 re f
Q
"""

# Page 2: a coarse grey ramp plus one saturated block per channel. Flat, large
# areas -- if a comparison passes on page 1's glyph edges but fails here, the
# problem is colour handling, not anti-aliasing.
_ramp = []
for i in range(10):
    g = i / 9.0
    _ramp.append(b"%.4f %.4f %.4f rg %d 90 30 60 re f\n" % (g, g, g, i * 30))
PAGE2 = b"q\n1 1 1 rg 0 0 300 160 re f\n" + b"".join(_ramp) + b"""1 0 0 rg 0 40 100 40 re f
0 1 0 rg 100 40 100 40 re f
0 0 1 rg 200 40 100 40 re f
0 g
BT /F1 11 Tf 8 14 Td (page 2 - channel ramp) Tj ET
Q
"""


def assemble(objects) -> bytes:
    """Serialise a 1-based object list into an uncompressed, reproducible PDF."""
    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + body + b"\nendobj\n"

    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += b"%010d 00000 n \n" % off
    # No /ID: it would either be random (non-reproducible) or a lie. The file is
    # not encrypted and never incrementally updated, so nothing needs one.
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_at,
    )
    return bytes(out)


def build() -> bytes:
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 260] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(PAGE1) + PAGE1 + b"endstream",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 160] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(PAGE2) + PAGE2 + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    return assemble(objects)


# ---------------------------------------------------------------------------
# alpha.pdf -- the fixture that makes the alpha detectors live.
#
# WHAT EACH ELEMENT IS FOR. Same rule as golden.pdf: nothing is decorative.
#
#   * NO background fill at all. golden.pdf's first act is `1 1 1 rg 0 0 200 260
#     re f`, which is why its render is opaque everywhere. This page paints no
#     backdrop, so every pixel nothing else touches stays alpha 0 -- a large,
#     contiguous, fully transparent region with real content beside it. That is
#     what the TRANSPARENT-PIXEL HALO detector needs: a host that leaves stale
#     colour in its transparent pixels has somewhere to leave it.
#   * Two constant-alpha graphics states (/ca /CA 0.5 and 0.25) over three
#     overlapping rectangles. The overlaps produce a spread of DISTINCT partial
#     alpha values -- 0.25, 0.5, and the composites of the two -- rather than one
#     flat 50%, so a host that quantised or clamped alpha differently diverges in
#     more than one place. Tens of thousands of pixels with 0 < alpha < 255,
#     comfortably past the comparator's 64-pixel floor for scoring a
#     premultiply fit.
#   * An image XObject with an /SMask: the CUT-OUT. Its soft-mask is a diamond
#     with hard 0 and 255 plateaus and a graded rim, so the image contributes
#     fully transparent pixels, fully opaque pixels and a partial ring, all
#     inside one object. The RGB payload underneath is deliberately saturated and
#     varies across the whole tile INCLUDING the masked-out corners: if anything
#     in the pipeline forgets to honour the mask, the wrong pixels are loud
#     rather than subtle.
#   * Text under 50% alpha, so glyph edges carry partial alpha too -- anti-
#     aliasing and alpha interacting is where the halo actually shows up in a
#     real document.
#
# Page size 180x220 pt, one page. Small on purpose, same reasoning as golden.pdf.

_CUT_W = 16
_CUT_H = 16


def _cut_rgb() -> bytes:
    """16x16 saturated RGB tile. Varies over the whole tile, corners included."""
    px = bytearray()
    for y in range(_CUT_H):
        for x in range(_CUT_W):
            px.append((x * 17) & 0xFF)
            px.append((y * 17) & 0xFF)
            px.append((255 - x * 8 - y * 8) & 0xFF)
    return bytes(px)


def _cut_smask() -> bytes:
    """16x16 DeviceGray soft mask: a diamond with hard plateaus and a graded rim.

    Integer arithmetic on purpose -- this file must regenerate byte-for-byte, and
    a float expression here would eventually be the reason it did not."""
    px = bytearray()
    for y in range(_CUT_H):
        for x in range(_CUT_W):
            # Manhattan distance from the tile centre, doubled to stay integral.
            d = abs(2 * x - (_CUT_W - 1)) + abs(2 * y - (_CUT_H - 1))
            if d <= 10:
                px.append(255)
            elif d >= 22:
                px.append(0)
            else:
                px.append(255 - (d - 10) * 255 // 12)
    return bytes(px)


ALPHA_PAGE = b"""q
1 0 0 rg 12 148 74 58 re f
/GS50 gs 0 0 1 rg 48 126 92 58 re f
/GS25 gs 0 0.6 0 rg 18 98 144 32 re f
Q
q
/GS50 gs 0 g
BT /F1 15 Tf 14 76 Td (ALPHA CUT) Tj ET
Q
q
118 0 0 62 32 8 cm
/Cut Do
Q
"""


def build_alpha() -> bytes:
    rgb = _cut_rgb()
    smask = _cut_smask()
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 180 220] /Group "
        b"<< /S /Transparency /CS /DeviceRGB /I true >> /Resources << "
        b"/ExtGState << /GS50 4 0 R /GS25 5 0 R >> /XObject << /Cut 6 0 R >> "
        b"/Font << /F1 9 0 R >> >> /Contents 8 0 R >>",
        b"<< /Type /ExtGState /ca 0.5 /CA 0.5 >>",
        b"<< /Type /ExtGState /ca 0.25 /CA 0.25 >>",
        b"<< /Type /XObject /Subtype /Image /Width %d /Height %d /ColorSpace "
        b"/DeviceRGB /BitsPerComponent 8 /SMask 7 0 R /Length %d >>\nstream\n"
        % (_CUT_W, _CUT_H, len(rgb)) + rgb + b"\nendstream",
        b"<< /Type /XObject /Subtype /Image /Width %d /Height %d /ColorSpace "
        b"/DeviceGray /BitsPerComponent 8 /Length %d >>\nstream\n"
        % (_CUT_W, _CUT_H, len(smask)) + smask + b"\nendstream",
        b"<< /Length %d >>\nstream\n" % len(ALPHA_PAGE) + ALPHA_PAGE + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    return assemble(objects)


KINDS = {"golden": build, "alpha": build_alpha}


def _write(path, data):
    with open(path, "wb") as fh:
        fh.write(data)
    print("wrote %s (%d bytes)" % (path, len(data)))


if __name__ == "__main__":
    argv = sys.argv[1:]
    if argv[:1] == ["--all"]:
        out_dir = argv[1] if len(argv) > 1 else os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "fixtures")
        for name, fn in KINDS.items():
            _write(os.path.join(out_dir, name + ".pdf"), fn())
        sys.exit(0)
    kind = "golden"
    if argv[:1] == ["--kind"]:
        kind = argv[1]
        argv = argv[2:]
        if kind not in KINDS:
            sys.exit("unknown fixture kind %r (want one of %s)" % (kind, ", ".join(sorted(KINDS))))
    _write(argv[0] if argv else "fixture.pdf", KINDS[kind]())
