#!/usr/bin/env python3
"""Generate the golden-image fixture PDF used by the Windows headless harness.

    portable/win/tests/make_fixture_pdf.py [out.pdf]

The fixture is committed, so this script exists to document how it was made and
to let it be regenerated byte-for-byte. It writes a hand-assembled, uncompressed
PDF: no MuPDF, no reportlab, no dependency that could drift and silently change
the golden image under the tests.

WHY THE PAGE LOOKS LIKE THIS. Every element is here to make one specific port
bug visible in a pixel comparison; nothing is decorative.

  * Asymmetric top-to-bottom (red band high, blue band low) so a VERTICAL FLIP
    -- the single most common bug when moving between a y-up rasteriser and a
    y-down blit target -- turns into a large, obvious colour difference rather
    than a subtle one. A vertically symmetric fixture would hide it completely.
  * Pure-red and pure-blue regions of unequal area so an RGB/BGR CHANNEL SWAP
    is unmissable and is not confusable with the flip (the flip moves the bands,
    the swap recolours them in place).
  * A green block and a black/grey ramp so a swap that only touches R and B is
    still distinguishable from one that touches all three.
  * Text and hairline rules so ANTI-ALIASING and hinting differences between the
    two rasterisers show up somewhere, and the tolerance can be measured on real
    glyph edges instead of on flat fill.
  * Page 2 is deliberately a different size from page 1, so a probe that reports
    only one page size, or a layout that assumes uniform pages, fails loudly.

Page 1 is 200x260 pt, page 2 is 300x160 pt. Small on purpose: the whole point is
that a render at zoom 2 is a few hundred KB, so a golden PNG can live in git.
"""

import sys

# Content stream for page 1. PDF user space: origin bottom-left, y increases UP.
# So "top" here means high y.
PAGE1 = b"""q
1 1 1 rg 0 0 200 260 re f
1 0 0 rg 10 200 180 50 re f
0 0.65 0 rg 10 150 80 40 re f
0.5 0.5 0.5 rg 100 150 90 40 re f
0 0 1 rg 10 60 180 40 re f
0 0.55 0.6 rg 10 20 90 40 re f
0.8 0 0.55 rg 100 20 90 40 re f
0 g
BT /F1 18 Tf 16 118 Td (SPDF WIN) Tj ET
BT /F1 9 Tf 16 106 Td (golden fixture page 1) Tj ET
0 g 1 w 10 136 m 190 136 l S
0 g 0.4 w 10 112 m 190 112 l S
0 0 0 rg 150 210 30 30 re f
1 1 1 rg 158 218 14 14 re f
Q
"""

# Page 2: a coarse grey ramp plus one saturated block per channel. Flat, large
# areas -- if a comparison passes on page 1's glyph edges but fails here, the
# problem is colour handling, not anti-aliasing.
_ramp = []
for i in range(10):
    g = i / 9.0
    _ramp.append(b"%.4f %.4f %.4f rg %d 90 30 60 re f\n" % (g, g, g, i * 30))
PAGE2 = b"q\n1 1 1 rg 0 0 300 160 re f\n" + b"".join(_ramp) + b"""1 0 0 rg 0 40 100 40 re f
0 1 0 rg 100 40 100 40 re f
0 0 1 rg 200 40 100 40 re f
0 g
BT /F1 11 Tf 8 14 Td (page 2 - channel ramp) Tj ET
Q
"""


def build() -> bytes:
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 260] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(PAGE1) + PAGE1 + b"endstream",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 160] "
        b"/Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>",
        b"<< /Length %d >>\nstream\n" % len(PAGE2) + PAGE2 + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % i + body + b"\nendobj\n"

    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += b"%010d 00000 n \n" % off
    # No /ID: it would either be random (non-reproducible) or a lie. The file is
    # not encrypted and never incrementally updated, so nothing needs one.
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_at,
    )
    return bytes(out)


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "fixture.pdf"
    data = build()
    with open(path, "wb") as fh:
        fh.write(data)
    print("wrote %s (%d bytes)" % (path, len(data)))
