# shenzhenpdf.spec — binary RPM for the GTK4 frontend (Fedora).
#
# The binary is compiled beforehand by build-rpm.sh (make -C portable
# linux-gtk4 inside the shenzhen-build-fedora container), so this spec has no
# %build section; it only stages files, mirroring build-deb.sh's install tree.
#
# rpmbuild must be invoked with these macros defined (build-rpm.sh does):
#   spdf_version  package version (SPDF_APP_VERSION, e.g. 26.7.17)
#   spdf_src      absolute path to the repo checkout
#   spdf_bin      absolute path to the built ShenzhenPDF-gtk4 binary

# Prebuilt binary: no debuginfo subpackage to extract.
%global debug_package %{nil}

Name:           shenzhenpdf
Version:        %{spdf_version}
# Plain "1" (no %%{?dist}) so the artifact name is stable across Fedora
# releases, like the deb: shenzhenpdf-<version>-1.<arch>.rpm.
Release:        1
Summary:        Fast, tabbed PDF reader with on-device OCR and translation

# The application sources carry GPL-3.0 (COPYING at the repo root, SumatraPDF
# lineage); the statically linked MuPDF engine is AGPL-3.0-or-later
# (mupdf/COPYING), which governs the combined binary.
License:        AGPL-3.0-or-later AND GPL-3.0-or-later
URL:            https://github.com/casimir-engineering/shenzhen-pdf

# Shared-library requirements (gtk4, libadwaita, openssl-libs, glibc) are
# auto-generated by rpm's find-requires from the linked sonames — no explicit
# Requires needed.
Recommends:     xdg-utils
Suggests:       ocrmypdf
Suggests:       tesseract

%description
ShenzhenPDF opens PDFs (and XPS, EPUB, CBZ, images) instantly, keeps
documents in tidy tabs, and does OCR and translation entirely on-device.
GTK4 frontend sharing its core with the macOS app.

%install
install -Dm755 %{spdf_bin} %{buildroot}%{_bindir}/shenzhenpdf
install -Dm644 %{spdf_src}/portable/linux/pkg/shenzhenpdf.desktop \
    %{buildroot}%{_datadir}/applications/shenzhenpdf.desktop
for size in 16 32 48 128 256; do
    install -Dm644 %{spdf_src}/gfx/ShenzhenPDF-${size}x${size}x32.png \
        %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/shenzhenpdf.png
done
install -Dm644 %{spdf_src}/portable/linux/pkg/minisign.pub \
    %{buildroot}%{_datadir}/shenzhenpdf/minisign.pub
install -Dm644 %{spdf_src}/COPYING \
    %{buildroot}%{_defaultlicensedir}/%{name}/COPYING
install -Dm644 %{spdf_src}/mupdf/COPYING \
    %{buildroot}%{_defaultlicensedir}/%{name}/COPYING.mupdf

# No %%post scriptlets: Fedora updates the desktop database and icon cache via
# file triggers shipped in desktop-file-utils / gtk-update-icon-cache.

%files
%{_bindir}/shenzhenpdf
%{_datadir}/applications/shenzhenpdf.desktop
%{_datadir}/icons/hicolor/*/apps/shenzhenpdf.png
%dir %{_datadir}/shenzhenpdf
%{_datadir}/shenzhenpdf/minisign.pub
%license %{_defaultlicensedir}/%{name}/COPYING
%license %{_defaultlicensedir}/%{name}/COPYING.mupdf

%changelog
# Versioning lives in portable/linux/gtk4/spdf_app.h; no per-release entries.
